package it.polimi.deib.provaFinale2014.matteo.daverio_valerio.demaria;

import java.io.Serializable;

public enum ComandiSocket implements Serializable{
	MOVIMENTO_PECORA_NERA,
	CAMBIO_TURNO,
	FASE_FINALE,
	MOVIMENTO_PASTORE, ABBATTIMENTO,ACCOPPIAMENTO, MOVIMENTO_PECORA, ACQUISTO_TESSERA,
	RICHIESTA_DI_MOSSA,
	INVIO_PARTITA,
	RICHIESTA_NOME,RICHIESTA_PASSWORD,AUTENTICAZIONE_RIUSCITA,AUTENTICAZIONE_FALLITA,
	LOG_IN
}
