package it.polimi.deib.provaFinale2014.matteo.daverio_valerio.demaria;

public enum EccezioniDiGioco {
 IMPOSSIBILE_PROCREARE,REGIONE_ILLEGALE,TIPO_REGIONE_ILLEGALE,STRADA_ILLEGALE,MOVIMENTO_INVALIDO,SOLDI_INSUFFICENTI,CARTE_FINITE,NO_PECORE_IN_REGIONE
}
